### ISSUE TITLE
I try destroy and I faced with this error

### ISSUE THREAD

**Issue by rafilkmp3** [jonathanio/terraform-module-s3-cloudfront#5]
Error deleting S3 Bucket: BucketNotEmpty

can you include maybe a variable with enable the following option in s3 resources.

force_destroy = true

tks in advance

**Comment by rafilkmp3** [comment]
related with https://github.com/jonathanio/terraform-module-s3-cloudfront/pull/6

**Comment by jonathanio** [comment]
Fixed. Closed by #6.
